baseURL = 'https://ktmenergysolutions.com'
languageCode = 'en-us'
paginate = 6
theme= "coHub"
title = 'KTM Energy Solutions'
 

  # Main Menu
  [[menu.Main]]
  name = "Our projects"
  url= "#gallery"
  weight = 1
  [[menu.Main]]
  name = "Why us?"
  url= "#service"
  weight = 1
  [[menu.Main]]
  name = "About us"
  url= "/about"

[params]
  # theme_overrides = "css/overrides.css"
  aboutPageURL = "about"
  contactLink = "contact"
  copyright = "© {year} <a target=\"_blank\">KTM Energy Solutions </a>"
  fabFormURL =  ""
  logo = "images/ktm-logo.png"
  footerlogo = "images/ktm-logo.png"

  [params.address]
  address = "Goce Delchev 43, 2000 Shtip, Macedonia"
  email = "naracki@ktm-es.com"
  openingDesc = "Give us a call or drop by anytime, we endeavour to answer all enquiries within 24 hours on business days."
  openingHours = "We are open from 08:00 - 16:00 Mon-Fri"
  phone = "+38978590599"

  # Social icons
  [[params.social]]
  icon = "ti-facebook"
  url = "https://www.facebook.com/profile.php?id=100083385300549"
  weight = 1
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/ktm.energysolution/"
  weight = 2
  
  